### ISSUE TITLE
Клавиатура

### ISSUE THREAD

**Issue by qarkai** [yumata/lampa#1]
Пожалуйста, добавьте возможность использовать нативный виджет клавиатуры.

**Comment by yumata** [comment]
В vplay было много с ней проблем, то не влезает в экран, то не появляется, то не исчезает, то не сохраняет текст и многое другое. Я же не хочу парится по этому поводу, встроенная отлично работает и не чего не загораживает.

**Comment by qarkai** [comment]
keypad.js работает очень плохо. Как минимум не поддерживает ввод с физической клавиатуры.
