### ISSUE TITLE
Не отображаются некоторые элементы интерфейса

### ISSUE THREAD

**Issue by novel55** [yumata/lampa#100]
Не отображаются некоторые элементы интерфейса при локальном запуске. Пробовал на двух локальных серверах через браузер тв и через msx тоже локально.Но если через разместить на хостинге то всё норм.Не могу понять почему так?
[https://pastenow.ru/FBRJD](url)
[https://pastenow.ru/FBRK7](url)
[https://pastenow.ru/FBRKR](url)
[https://pastenow.ru/FBRL8](url)
![photo_2021-12-14_12-37-18](https://user-images.githubusercontent.com/29304120/145954991-293fe16f-f4a0-4fcf-90db-d0b77acc24a0.jpg)
![photo_2021-12-14_12-40-32](https://user-images.githubusercontent.com/29304120/145954995-b48cfc12-894a-4765-8124-66a9f4ae0955.jpg)
![photo_2021-12-14_12-43-02](https://user-images.githubusercontent.com/29304120/145954998-a6046e63-8dfb-4b0b-bc60-8c669605c67c.jpg)
![photo_2021-12-14_12-43-09](https://user-images.githubusercontent.com/29304120/145955000-771f580d-f486-47f5-8a46-57ff2c715704.jpg)

**Comment by yumata** [comment]
Зайдите через браузер и смотрите в консоли по какому адресу грузятся картинки, может что-то не так делайте.
