### ISSUE TITLE
не устанавливается виджет на samsung ue49ks8000

### ISSUE THREAD

**Issue by MrKrab81** [yumata/lampa#101]
При установке виджета через Tizen Studio возникает следующая ошибка
[ide-20211221_154037.log](https://github.com/yumata/lampa/files/7755789/ide-20211221_154037.log)
[ide-20211221_162620.log](https://github.com/yumata/lampa/files/7755779/ide-20211221_162620.lo
В чем может быть проблема?

**Comment by omariok** [comment]
Не знаю что за ссылку вы выложили, тоже были проблемы с установкой через Studio и Dark, нашел где-то в вк Lampa Updated и все отлично встало)
Вообще можете dark smart оплатить около 50р донатом, там в каталоге виджетов он есть и без проблем устанавливается

**Comment by yumata** [comment]
Есть еще один способ, это создать виджет свой, затем в него закинуть исходники с виджета лампы и установить. Мне так помогло, более подробнее спрашивайте в группе.
