### ISSUE TITLE
Выбор плеера для проигрывания видео

### ISSUE THREAD

**Issue by nrcmn** [yumata/lampa#104]
Можно как-то поправить выбор плеера, сейчас это выглядит так:

![image](https://user-images.githubusercontent.com/10852082/147413326-30e00081-4ab9-416c-98ce-9b26cfa808d5.png)

с пульта телевизора выбрать плеер нет возможности, только подключать мышь, но так как не видно галочки "Выбрать по умолчанию", приходится каждый раз мышью выбирать.

MiTV 3S
Android 6.0.1

**Comment by nrcmn** [comment]
Lampa 1.3.7

**Comment by yumata** [comment]
По андроиду писать в эту группу https://t.me/lampa_android
