### ISSUE TITLE
Загрузка торрент файла возможна?

### ISSUE THREAD

**Issue by e357sn** [yumata/lampa#108]
Вопрос к разработчику лампы. Можно сделать чтобы лампа не отдавала ссылку на файл .torrent а сначала скачивала а потом отдавала торсерву. Потому что торсервер у меня на vds а жакет локальный и соответственно торсерв не может такую ссылку от лампы загрузить

**Comment by yumata** [comment]
Нет, ограничения CORS и т.д.
