### ISSUE TITLE
Не работает встроенный плеер Web OS

### ISSUE THREAD

**Issue by Joy096** [yumata/lampa#110]
Телевизор LG UH6507, прошивка 05.60.25. Работа через виджет, в настройках - проигрывание через встроенный плеер web OS. При запуске любого фильма ничего не происходит, плеер web os не запускается, встроенный плеер Lampы работает корректно. 
При работе через MSX - плеер web OS запускается (только позицию где закончил смотреть фильм не запоминает).

**Comment by aabytt** [comment]
@yumata дело в разрешениях, мне уже кто-то на вебос 3.х писал про такое
нужно поправить appinfo.json
```
	"requiredPermissions": [
		"all",
	],
```
или вообще убрать параметр `requiredPermissions`, достаточно того что есть по умолчанию

**Comment by Joy096** [comment]
Это в таком случае нужно вручную править ipk и ее ставить? Я с маркета webosapp.club устанавливал

**Comment by Joy096** [comment]
> @yumata дело в разрешениях, мне уже кто-то на вебос 3.х писал про такое нужно поправить appinfo.json
> 
> ```
> 	"requiredPermissions": [
> 		"all",
> 	],
> ```
> 
> или вообще убрать параметр `requiredPermissions`, достаточно того что есть по умолчанию

Это в таком случае нужно вручную править ipk и ее ставить? Я с маркета webosapp.club устанавливал

**Comment by aabytt** [comment]
> Это в таком случае нужно вручную править ipk и ее ставить? Я с маркета webosapp.club устанавливал

можно поправить в уже установленном на тв файле, или дождитесь когда будет обновленный релиз ipk

**Comment by yumata** [comment]
Поправлю в следующем релизе.
