### ISSUE TITLE
не находит торренты

### ISSUE THREAD

**Issue by pyzone2012** [yumata/lampa#111]
Samsung TV, Jackett, Torrserver. Столкнулся с ситуацией, когда при поиске выдает, что "здесь пусто. поиск не дал результатов". Допускаю, что это вина Jackett, но "крайним" получается lampa, да и разработчик намного более в теме.
Вышел из ситуации поиском через браузер и добавлением торрента через Torrserver adder.
Искал фильм "Престиж" (2006 г.)

**Comment by impr3ssi0n** [comment]
Да, далеко не все находит. И тут даже дело не в формате. Так как перестал находить свежие релизы. На трекере они есть, в лампе с jackett нет(

**Comment by Darkensand** [comment]
Нужно поправить у меня такое же

**Comment by yumata** [comment]
Проблема телевизора, пишут что помогает смена днс или переключения на торлук.
