### ISSUE TITLE
Воспроизведение видео

### ISSUE THREAD

**Issue by Wegalodon** [yumata/lampa#112]
Здравствуйте. При возобновлении воспроизведения 4к видео после паузы появляются фризы во встроенном плеере. Видео может зависать на несколько секунд, невозможно смотреть дальше. Помогает перезагрузка телевизора. Такое впечатление, что забивается оперативка. Торрсервер и виджет установлены на телевизоре. LG 50UP76006LC.

**Comment by greenProgrammerAlbert** [comment]
поставьте торрсервер на другое устройство, оперативка телека перегружается, поэтому и фризит

**Comment by Va1er0n82** [comment]
Здравствуйте. Добавьте, пожалуйста, в плеер Lampa скорость воспроизведения кратную 0,1x. Часто смотрю в ускоренной виде, чтоб тратить меньше времени на просмотр. Спасибо.

**Comment by greenProgrammerAlbert** [comment]
пишите это не сюда, а в офф.группу в телеграмме, и я не разработчик lampa
