### ISSUE TITLE
Проблема с поиском онлайн стримов

### ISSUE THREAD

**Issue by moook-git** [yumata/lampa#114]
На фильмы «Люси» «Такси» «Мстители» «Мадагаскар» и тд при поиске онлайн (rezka, videocdn, kinobase) выдает не все фильмы. К примеру есть все фильмы где в названии встречается Люси, но нет самого фильма который на обложке
![FA1897F8-3931-483C-80A0-E3943328CCAC](https://user-images.githubusercontent.com/85396539/151709802-729febb7-ee36-4f3c-af02-22c3f7c34d1f.jpeg)

Samsung Tizen, приложение запускается через MSX, ссылка плагина http://arkmv.ru/vod

**Comment by yumata** [comment]
Есть там, в плагине http://jin.energy/online.js точно есть.
