### ISSUE TITLE
Виджеты 

### ISSUE THREAD

**Issue by Darkensand** [yumata/lampa#115]
Добрый день хорошо было бы добавить виджеты на smart TV такие как с популярными фильмами сейчас смотрят новинки фильмов новинки сериалов!
Заранее спасибо!

**Comment by muravell** [comment]
переустановил себе на Tizen виджет 1.3.7 в манифесте которого есть разрешения на доступ к микрофону для голосового поиска но телек выдает такую же ошибку ,- нет доступа к микрофону. Голосовой поиск работает вообще ?

**Comment by Darkensand** [comment]
>  переустановил себе на Tizen виджет 1.3.7 в манифесте которого есть разрешения на доступ к микрофону для голосового поиска но телек выдает такую же ошибку ,- нет доступа к микрофону. Голосовой поиск работает вообще ?

Но у меня с голосовым поиском проблем нет

**Comment by scholwa** [comment]
Доброе время суток. Всё классно, но можно добавить кнопочку для выхода , например наверху рядом с настройками или с лева в контекстном меню? Уже установил сохранять только одну страницу, а когда листаешь назад для выхода приходиться перелистывать всю историю за время включения.
В общем кнопочка выйти будет удобна
Спасибо

**Comment by yumata** [comment]
> Доброе время суток. Всё классно, но можно добавить кнопочку для выхода , например наверху рядом с настройками или с лева в контекстном меню? Уже установил сохранять только одну страницу, а когда листаешь назад для выхода приходиться перелистывать всю историю за время включения. В общем кнопочка выйти будет удобна Спасибо

Зажать и удерживать кнопку (назад)

**Comment by yumata** [comment]
> 

Не понял, что еще за виджеты?
