### ISSUE TITLE
Вопрос проигрывания субтитров из папок

### ISSUE THREAD

**Issue by SplitSpirit** [yumata/lampa#116]
Всё работает идеально, но вот во время просмотра аниме зачастую субтитры в торренте расположены в отдельной папке и разумеется плееры при воспроизведении их не видят. Вот и появился такой вопрос, а возможно ли добавить поддержку подгрузки из вложенных папок на монер плееров пк? Ведь их как то надресеровали подхватывать из папок или в нашем случае это невозможно реализовать?

ЗЫ: спасибо за такое удобное и приятное приложение

**Comment by aabytt** [comment]
Торрсервер вроде как не даёт ссылки на эти файлы, поэтому не получится использовать их как источник субтитров.
А так, lg webos например, позволяет к любому видео добавить и отобразить субтитры по прямой ссылке на файл субтитров.

**Comment by yumata** [comment]
Готово, теперь плеер может проигрывать avi файлы с сабами.
