### ISSUE TITLE
Графические баги

### ISSUE THREAD

**Issue by ilya-vdovenko** [yumata/lampa#118]
Tizen 2016 года, FHD. Все настройки интерфейса упрощены.

- [белые полосы при выборе в боком меню]( https://imgur.com/a/Qa8AWre)
- [как первое только с персонами](https://imgur.com/a/NGLS4jq)
- [баг с подгрузкой карточек (не важно какой вариант в настройках)](https://imgur.com/a/kOnYISE)
- [частый баг с правым боковым подменю](https://imgur.com/a/9pSyU7m)
- [прорисовка элем. управления в плеере](https://imgur.com/a/TnNMvoX)

**Comment by yumata** [comment]
Ну тут явно что-то с телеком не ладное, возможно из за не хватки графической памяти.

**Comment by ilya-vdovenko** [comment]
> Ну тут явно что-то с телеком не ладное, возможно из за не хватки графической памяти.

лол, а "недоделанное приложение" мы исключаем?
