### ISSUE TITLE
полностью перестал работать поиск

### ISSUE THREAD

**Issue by pyzone2012** [yumata/lampa#120]
Samsung TV, до вчерашнего дня (8.04) все работало, пользовался Jackett. Вчера перестал искать jackett, переключил на torlock. Утром 9.04 уже и torlock не ищет.
Обратил внимание на пункт Account в настройках, раньше его не замечал. Теперь уже нужна регистрация?
номер версии 1.3.7 от 23.12.21

**Comment by totavok8** [comment]
Проблема в TMDB (themoviedb) проект включил геоблок для рф (возможно и для ещё какой то страны)
Поэтому поиск не работает (лампа искала по нему)
Временное решение: Включить ВПН.

**Comment by GitUser200607** [comment]
А без этой базы никак нельзя? Лично мне постеры и описание не особо нужны.  На смарт-ТВ VPN уже не подключишь, в отличие от телефона.

**Comment by yumata** [comment]
Работает.
