### ISSUE TITLE
Features - отметки о просмотрах, нотификации

### ISSUE THREAD

**Issue by torquemada163** [yumata/lampa#124]
Здравствуйте! 
Прекрасное приложение, но хотелось бы иметь несколько функций, по типу, как в KinoPub:
- хотелось бы в карточке сериала иметь возможность отмечать просмотренные эпизоды
- очень бы пригодилось оповещение по электронной почте о появлении нового эпизода, доступного для просмотра

**Comment by usmanec** [comment]
@torquemada163 

1. насколько я понимаю у вас андройд, т.к. на внутреннем плеере отмечается просмотренные серии + имеется таймлайн с отметкой сколько просмотренно из скольки (с возможностью просмотра с момента окончания). Приложение под андройд пилил другой разработчик, так как запускается внешний плеер сколько вы просмотрели в нём и на какой серии остановились приложение не знает, хотя для некоторых плееров под Андройд сущест возможность получить текущую позицию просмотра и продолжительность фильма, разработчик apk этого не делал и скорее всего не будет (т.к. было объявлено что это финальная версия).
2. можно в закладки добавить нужный сериал, тогда уведомление о выходе серии прилетает в колокольчик, чем не устраивает?

**Comment by yumata** [comment]
1. Удерживать клавишу ОК и в контекстном меню отметить + серия отмечается после того как нажали не неё.
2. Добавить сериал в закладки и подключить бот @cubmybot
