### ISSUE TITLE
Не работает автозапуск следующей серии

### ISSUE THREAD

**Issue by Animaguss** [yumata/lampa#126]
Устройство Samsung TU8500 Tizen, плеер встроенный.

При просмотре через торсервер запуск следующей серии не работает, после окончания текущей серии просто черный экран.

**Comment by usmanec** [comment]
@Animaguss опция использовать буффер пред.загрузки включена?
тайзена нет, но на андройде с включенной опцией (на встренном TorrServe) ViMu падает с ошибкой, так как url в плейлистах содержит preload, а не play  вконце. При этом основной url запускаемого видео корректное но виму его не учитывает при запуске плейлистов (именно поэтому в других плеерах (MX например) серия запускается, но на следующую не переключается.
С отключенной опцией переключение серий и виму работают корректно.

**Comment by Pro100x3mal** [comment]
Такая же проблема на атв. Если включить встроенный в Ламу клиент торрсервера там же включить буфер предзагрузки - плеер виму падает с ошибкой при переключении серии в сериалах. Если буфер предзагрузки выключить - все работает

**Comment by yumata** [comment]
Исправлено.
