### ISSUE TITLE
Ускоренный просмотр во встроенном плеере на Tizen

### ISSUE THREAD

**Issue by kpdeath** [yumata/lampa#133]
Проблема: некоторые сериалы/фильмы хочется смотреть в ускоренном режиме (на телевизорах Самсунг)
Решение: добавить во встроенный плеер возможность просмотра в ускоренном режиме. Желательно скорости: 1/1.25/1.75/2

спасибо за ваше приложение!

**Comment by yumata** [comment]
Хммм, наверно можно добавить.

**Comment by yumata** [comment]
Добавил, но звук есть только на hls потоках. Например на балансере collaps. В остальных без звука, в плеере от Tizen есть скорости только 2х, 4х, 8х, 12х и тоже без звука. Надо было брать LG :D
