### ISSUE TITLE
Mac OS torrent нет звука

### ISSUE THREAD

**Issue by alexunderboots** [yumata/lampa#136]
При просмотре через любой браузер - нет звука если смотришь торренты. А онлайн-кинотеатры - звук есть

**Comment by Dalveral** [comment]
Чуть больше года прошло. Может быть появились решения проблемы?)

**Comment by aabytt** [comment]
> Чуть больше года прошло. Может быть появились решения проблемы?)

Приложение на macOS с возможностью подключить внешний плеер
