### ISSUE TITLE
[wiki] Инструкция для установки TorrServer в Linux

### ISSUE THREAD

**Issue by varlesh** [yumata/lampa#145]
### Скачиваем TorServer

Открываем терминал и вводим поочередно команды:

```
# Скачиваем
sudo wget -c https://github.com/YouROK/TorrServer/releases/download/MatriX.117/TorrServer-linux-amd64 -O /usr/bin/torrserver
# Даем право на выполнение
sudo chmod +x /usr/bin/torrserver
# Скачиваем юнит для systemd
sudo wget https://raw.githubusercontent.com/YouROK/TorrServer/master/torrserver.service -O /usr/lib/systemd/system/torrserver.service
# Фиксим пути к бинарнику и базе данных
sudo sed -i "s/path\/to\/torrserver/usr\/bin\/torrserver/g" /usr/lib/systemd/system/torrserver.service
sudo sed -i "s/path\/to\/db\//tmp/g" /usr/lib/systemd/system/torrserver.service
# Включаем и запускаем юнит
sudo systemctl daemon-reload
sudo systemctl enable torrserver
sudo systemctl start torrserver
# Проверяем
xdg-open http://localhost:8090
```

Должна открыться вкладка браузера с TorrServer

![](https://i6.imageban.ru/out/2022/08/13/d2552d616b8a130b84e52fe314c1c055.png)

### Настройка

Теперь нам нужно узнать IP адрес нашего компьютера:

```
hostname -I | awk '{print $1}'
```

Также этот адрес можно посмотреть на вашем роутере:

![](https://i1.imageban.ru/out/2022/08/13/0db2c49bb8f8d30202d5699bccb097b7.png)

Далее мы заходим в приложение Lampa, `настройки` -> `Torserver` и вписываем туда наш `IP` адрес.

Если мы запускали Torrserver на Linux адрес будет: 192.168.1.102:8090 (у вас будет свой)

Если у вас TorrServer и Lampa установлены на одном устройстве, например телевизор с Android или ТВ-бокс с Android, то адрес будет такой: `127.0.0.1:8090` или `localhost:8090`

### ВАЖНО!!! 

Обязательно после IP адреса не забываем прописывать порт `:8090`

Torrserver для Lampa ДОЛЖЕН БЫТЬ обязательно не ниже `Matrix!!!`

На этом настройка завершена.

**Comment by yumata** [comment]
Добавил https://github.com/yumata/lampa/wiki/%D0%9D%D0%B0%D1%81%D1%82%D1%80%D0%BE%D0%B9%D0%BA%D0%B0-TorrServer-%D0%B2-Linux
