### ISSUE TITLE
[UI] Возрастной рейтинг в описании

### ISSUE THREAD

**Issue by varlesh** [yumata/lampa#148]
Было бы не плохо иметь возможность видеть возрастной рейтинг в описании фильма/сериала. Потому как, не все мультфильмы можно показывать маленьким детям. В API TMDB вроде доступна возможность:
https://developers.themoviedb.org/3/movies/get-movie-release-dates
https://developers.themoviedb.org/3/tv/get-tv-content-ratings
Пример индикатора:
![ranking](https://user-images.githubusercontent.com/8083855/185350228-f68e7ae0-f3c9-4387-9a66-3315aeae4c31.png)

**Comment by yumata** [comment]
Добавлен.

**Comment by varlesh** [comment]
Красавчик! Спасибо

**Comment by varlesh** [comment]
@yumata В сериалах отображается. В фильмах почему-то нет. Проверял на компе и телике.

**Comment by yumata** [comment]
Поправил.

**Comment by varlesh** [comment]
Спасибо. Когда закончатся идеи улучшения лампы, рассмотрите возможность сделать его более удобным в понимании для народа. Думаю простая подмена, поможет :)

Фильмы:
- G = 3+
- PG = 6+
- PG-13 = 13+
- R = 17+
- NC-17 = 18+

Сериалы:

- TV-Y = 3+
- TV-Y7 = 7+
- TV-G = 3+
- TV-PG = 6+
- TV-14 = 14+
- TV-MA = 17+

ЗЫ: Писал наугад, может где ошибся.

**Comment by yumata** [comment]
Наугад не хорошо писать)) Надо бы точнее результаты.

**Comment by varlesh** [comment]
С TV-Y ошибся (уже поправил). Из [википедии](https://en.wikipedia.org/wiki/TV_Parental_Guidelines):
> Эта программа предназначена для всех детей.

Ну остальные вроде совпадают.

**Comment by yumata** [comment]
Добавил.

**Comment by varlesh** [comment]
Вот теперь здорово!
