### ISSUE TITLE
Mixed content. Не работает редирект с http://www.youtube.com/iframe_api на https://www.youtube.com/iframe_api в index.html

### ISSUE THREAD

**Issue by Pro100x3mal** [yumata/lampa#175]
Если лампа работает по https, то не работает редирект с
<script src="http://www.youtube.com/iframe_api" async></script>

на

<script src="https://www.youtube.com/iframe_api" async></script>
И соответственно появляется ошибка mixed content

**Comment by yumata** [comment]
Теперь лампа не работает на https

**Comment by Pro100x3mal** [comment]
На своем впс запустил по https. Работает.
