### ISSUE TITLE
Кинориум API

### ISSUE THREAD

**Issue by qarkai** [yumata/lampa#188]
Добавить альтернативу TMDB: https://kinorium.com/insider/api/
Плюсы:
* Более полная база фильмов, чем TMDB. Примерно соответствует "Кинопоиску".
* Нет региональных ограничений, не заблокирован РКН.

Минусы:
* API закрыто, доступ по запросу.

**Comment by yumata** [comment]
Один минус перекрывает все плюсы))

**Comment by totavok8** [comment]
выдают не каждому, а то и игнорирует во все.
Запрашивал апи у них 2 месяца назад и месяц назад. Письма игнорируют они.

**Comment by qarkai** [comment]
Реклама.
