### ISSUE TITLE
Adding an export of video stream to external video player

### ISSUE THREAD

**Issue by Gonochnik** [yumata/lampa#219]
Добрый день.
В настоящее время в LAMPA имеется выгрузка стрима в Infuse по x-callback-url.
По просьбе сообщества, разработчики SVP (SmoothVideo Project) в последней версии, по аналогии с Infuse, добавили код для экспорта стрима (What's New: "+ "svplayer://" scheme for x-callback-url (same syntax as in VLC)")

Прошу добавить поддержку в Лампу по аналогии 'infuse_url' = 'infuse://x-callback-url/play?url=': 
синтаксисом типа 'svp_url' = 'svplayer://x-callback-url/play?url='

**Comment by yumata** [comment]
Это андроид? Или ios? Или appleTV?

**Comment by aabytt** [comment]
@Gonochnik 
что-то на ios не рабочий синтаксис (как у VLC)

**Comment by Gonochnik** [comment]
> Это андроид? Или ios? Или appleTV?

Речь про AppleTV (на iOS же ее не портировали пока в Test Flight). 
На Андроиде пофиг, тупо при первом запуске в списке находится любой проигрыватель (хоть MX Player, хоть SVP и прочие...) и выбирается по умолчанию.

**Comment by aabytt** [comment]
> Речь про AppleTV (на iOS же ее не портировали пока в Test Flight). 
На iOS пользуются как pwa

**Comment by chainikdn** [comment]
вон на два топика ниже то же самое ;)
https://github.com/yumata/lampa/issues/216

**Comment by aabytt** [comment]
В лампе на iOS для vlc вообще работает формат vlc://
Для svp не работает

> svplayer://x-callback-url/stream?url=
С этим тоже видео не стартует

**Comment by chainikdn** [comment]
Проверка:
1. должна быть последняя версия 1.3.1
2. команда примерно такого вида:
![IMG_0079](https://github.com/yumata/lampa/assets/9394230/d8520f49-fb30-4c5a-8f5b-4b6231a470db)
3. сафари - тык на ссылке - поделиться - open in svp
4. профит, всё работает

**Comment by aabytt** [comment]
Простые прямые ссылки открываются, да.
Можно просто в адресной строке сафари вставить и проверить
svplayer://x-callback-url/stream?url= https://media.w3.org/2010/05/sintel/trailer.mp4

А вот ссылки с торрсервера не воспроизводятся, в отличии от vlc/infuse/nplayer
Пример:

svplayer://x-callback-url/stream?url= http://127.0.0.1:8090/stream/Aquaman.and.the.Lost.Kingdom.2023.DUB.WEB-DLRip.x264.seleZen.mkv?link=107d98b5888468cdce6527c231574a36fd4d9e0b&index=1&play

**Comment by chainikdn** [comment]
Так конечно оно должно быть закодировано, иначе это не валидный URL. И для VLC оно должно быть точно так же закодировано.

**Comment by aabytt** [comment]
В iOS с vlc как раз работает с минимальным [преобразованием](https://github.com/yumata/lampa-source/blob/8aff53903bfc02f1c5f20aed2cec92e1d7264b1e/src/interaction/player.js#L686) ссылки в формате `vlc:// + ссылка`

**Comment by chainikdn** [comment]
Почему-то не открывается на Apple TV.
На iOS всё четко, а на Apple TV как будто не ту схему использует - "URL can't be shown".
Если я в info.plist SVPlayer-а прикидываюсь VLC - меняю "svplayer" на "vlc-x-callback", и в Лампе выбираю "VLC", то всё работает. Меняю обратно на svplayer - не работает.
Билд 52 из TestFlight от 4 марта.

**Comment by Gonochnik** [comment]
> На iOS всё четко, а на Apple TV как будто не ту схему использует - "URL can't be shown".

Прошел год, решения под AppleTV так и не появилось?

**Comment by chainikdn** [comment]
Есть мнение что чтоб оно работало, в Info.plist лампы в LSApplicationQueriesSchemes надо добавить схему "svplayer".
Не знаю, почему оно работает в iOS, не знаю где посмотреть текущее содержание Info.plist.
