### ISSUE TITLE
Еще одно улучшение для ПКашников

### ISSUE THREAD

**Issue by BazZziliuS** [yumata/lampa#227]
Хочу предложить добавить возможность открывать меню действий 2-ым кликом или ПКМ

![image](https://github.com/yumata/lampa/assets/18011884/26080db7-addb-4059-ab92-1f22c9e944c4)

**Comment by yumata** [comment]
Хм, ну да логично, надо будет добавить.

**Comment by BazZziliuS** [comment]
https://github.com/yumata/lampa-source/commit/93f621b0d154cbf5492bf84246e68ca9cdb9f5e6
