### ISSUE TITLE
Ошибка. Проблема с воспроизведением видео Error: Failed to set the 'currentTime' property on 'HTML Media Element': The provided double value is non-finite.

### ISSUE THREAD

**Issue by hybtwwwww** [yumata/lampa#244]
Проблема с воспроизведением видео, которая не исправилась даже полным сбросом приставки до заводских настроек.

Как сказал интернет: 
Эта ошибка означает, что приложение Lampa пытается установить время воспроизведения видео на значение, которое не является числом. Это может произойти, если время, которое передается, не определено или является недопустимым.

Проще говоря, приложение не может понять, на какой момент времени нужно перемотать видео, потому что получило неправильное значение. Это может быть вызвано ошибкой в самом приложении или проблемой с видеофайлом.

Попробуйте перезапустить приложение или устройство, а также убедитесь, что у вас установлена последняя версия Lampa. Если проблема не исчезнет, возможно, стоит обратиться в службу поддержки приложения.
Ничего из перечисленного не помогло, если кто то возьмётся за эту проблему, могу уточнить все остальное.
![20240817_032123](https://github.com/user-attachments/assets/48114532-6349-4077-9858-4bbf440a61ea)

**Comment by hybtwwwww** [comment]
Добавлю что такая проблема есть только на одном, конкретном девайсе, на котором впредь такого не было, на устройстве Android - телефоне все работает отлично.

**Comment by yumata** [comment]
Скорее всего битый таймкод и пытается перемотать на несуществующие время, или видео не успевает загрузится и передает продолжительность видео как не определено. В любом случаи попробую исправить этот баг.

**Comment by yumata** [comment]
Вроде бы исправил, надо проверить.

**Comment by hybtwwwww** [comment]
> Вроде бы исправил, надо проверить.

Да, все работает теперь, спасибо за быстрый отклик
