### ISSUE TITLE
Ошибка. Проблема с воспроизведением видео Error: Failed to set the 'currentTime' property on 'HTML Media Element': The provided double value is non-finite.

### ISSUE THREAD

**Issue by hybtwwwww** [yumata/lampa#246]
Ошибка в приложении: 
Error: Failed to set the 'currentTime' property on 'HTML Media Element': The provided double value is non-finite.
Пишет "Видео не найдено или повреждено" либо "Не удалось извлечь ссылку". Скорее всего проблема в битых таймкодах в плеере, ошибка возникала и раньше и появляется периодически.
Почините её уже навсегда, пожалуйста, пользуюсь параметром "msxplayer.ru", и плагином MOD'S в лампе.

**Comment by yumata** [comment]
Возможно исправил, но это не точно :D

**Comment by hybtwwwww** [comment]
Все ещё есть
