### ISSUE TITLE
Зависимость лампы от cub.red

### ISSUE THREAD

**Issue by ruskmv** [yumata/lampa#256]
Если cub.red недоступен, то пользоваться лампой невозможно, при проваливании в карточку получаем вечную загрузку. Думаю это не очень хорошо.

**Comment by yumata** [comment]
Этого можно избежать, если поставить свой впн и не использовать плагин TMDB Proxy

**Comment by yumata** [comment]
Действительно, была ошибка, не обрабатывалось исключения в комментариях под карточкой, теперь этот баг исправлен.
