### ISSUE TITLE
qBittorrent WebUI API Search

### ISSUE THREAD

**Issue by qarkai** [yumata/lampa#3]
Пожалуйста, добавьте парсер для результатов поиска qBittorrent https://github.com/qbittorrent/qBittorrent/wiki/WebUI-API-%28qBittorrent-4.1%29#search.

**Comment by smyhlin** [comment]
> Пожалуйста, добавьте парсер для результатов поиска qBittorrent https://github.com/qbittorrent/qBittorrent/wiki/WebUI-API-%28qBittorrent-4.1%29#search.

Не вижу необходимости, они(qbittorent) используют те же парсеры(у них вкладка поиска где предлагают скачать плагин - парсер) для поиска, у Jackett тот же функционал и даже больше.

**Comment by yumata** [comment]
Думаю джека и торлука вполне хватает.
