### ISSUE TITLE
Пульт. Проблема с навигацией в Android (apk)

### ISSUE THREAD

**Issue by eboboshka** [yumata/lampa#35]
Не работают кнопки навигации внутри приложения UP/LEFT/RIGHT/DOWN- это как кнопка ОК.
Кнопка MENU - не реагирует.
При этом кнопка RETURN работает корректно как назад.
Кнопка ОК работает нормально.

Использую проектор XGIMI H3 (v1.14.84) с ОС Android 8.0, в приложении apk 1.0.1 Lampa

**Comment by eboboshka** [comment]
Понял. Принял.

Все сюда - https://t.me/lampa_android

**Comment by qarkai** [comment]
> Понял. Принял.
> 
Закрой.
