### ISSUE TITLE
[Request] Добавить фильтр (год/рейтинг/страна/жанр/фильм-сериал)

### ISSUE THREAD

**Issue by AleXXXv1** [yumata/lampa#37]
Добрый день. Было бы не плохо добавить фильтр для выбора фильма/сериала по нужным критериям, сейчас доступен только каталог по жанрам, и этого не достаточно.

**Comment by antoniox32** [comment]
+ тоже хотел написать это в просьбу !

**Comment by antoniox32** [comment]
Эх, новую версию выпустили, а "хотелку" нашу так и не сделали  ((

**Comment by yumata** [comment]
Готово.
