### ISSUE TITLE
Где скачать кроме телеграмма? Не пользуюсь и не собираюсь)

### ISSUE THREAD

**Issue by VladimirYaYa** [yumata/lampa#43]
Где-то можно его новую версию скачать? Через само приложение не обновляется.

**Comment by Fatal1ty23** [comment]
Какая

**Comment by VladimirYaYa** [comment]
> Зачем тогда скачивать?

Это я про телеграмм писал, что не пользуюсь)
А приложение реально крутое. Спасибо за обновление.
Есть в планах управление для сенсорного экрана? На планшете не работает.
