### ISSUE TITLE
[Request] Аккаунты и синхронизация между устройствами

### ISSUE THREAD

**Issue by AleXXXv1** [yumata/lampa#47]
Планируете ли в дальнейшем добавить синхронизацию данных между устройствами?

**Comment by Ruich07** [comment]
Тоже интересует,сделал все как написано в вики,но синхрона нет у меня.

Для работы синхронизации необходимо зарегистрироваться на сайте https://gist.github.com

После регистрации необходимо сгенерировать личный токен, для этого переходим по этой ссылке https://github.com/settings/tokens/new?scopes=gist

Вас попросят потвердеть учётку паролем, подтвердите и далее следуйте инструкциям.

В поле Note укажите название, к примеру lampa
В поле Expiration выберите No expiration
Промотайте вниз и нажмите кнопку Create token
Полученный токен укажите в приложение lampa

**Comment by 7grad** [comment]
Тоже интересует,сделал все как написано в вики,но синхрона нет у меня.

Для работы синхронизации необходимо зарегистрироваться на сайте https://gist.github.com

После регистрации необходимо сгенерировать личный токен, для этого переходим по этой ссылке https://github.com/settings/tokens/new?scopes=gist

Вас попросят потвердеть учётку паролем, подтвердите и далее следуйте инструкциям.

В поле Note укажите название, к примеру lampa
В поле Expiration выберите No expiration
Промотайте вниз и нажмите кнопку Create token
Полученный токен укажите в приложение lampa

**Comment by Ruich07** [comment]
Я все так и сделал,токен вставил в настройках lampa,но все равно нет синхронизации.
--
Отправлено из Mail.ru для Android понедельник, 20 декабря 2021г., 19:09 +03:00 от 7grad  ***@***.*** :

**Comment by yumata** [comment]
Добавлена синхронизация через CUB

**Comment by Dalveral** [comment]
Возможно ли реализовать синхронизацию не через CUB?
