### ISSUE TITLE
[Request] кнопка "ещё" рядом с подборкой в категории

### ISSUE THREAD

**Issue by N1ckky** [yumata/lampa#48]
На данный момент кнопка находится в самом конце иконок с постерами. Хотелось бы добавить аккуратную кнопочку прямо рядом с названием подборки. Можно написать "отобразить больше" или "показать все" или просто "ещё".
Можно реализовать как в Ivi например - такая кнопка появляется слева от самого первого постера (на фотке прикладываю). При прокрутке вправо - кнопка скрывается естественно.
![IMG_20211013_213048](https://user-images.githubusercontent.com/54807747/137192246-4a265450-4d8b-4b63-8a2f-a996d7d794fb.jpg)
![IMG_20211013_213049](https://user-images.githubusercontent.com/54807747/137192260-7c882bc6-0c95-40e7-87fb-a1e9eee62aeb.jpg)

Но кнопку в конце тоже лучше оставить, так будет лаконично
![IMG_20211013_212806](https://user-images.githubusercontent.com/54807747/137191946-5be5d847-4d2b-40b5-912f-573a72af6395.jpg)
![IMG_20211013_212603](https://user-images.githubusercontent.com/54807747/137191963-bd64046a-2cf5-47d1-81d3-d09d3daadaca.jpg)

**Comment by yumata** [comment]
Добавил.
