### ISSUE TITLE
Блюрей торренты

### ISSUE THREAD

**Issue by poheto** [yumata/lampa#50]
#29 
1. Наглядное представление проблемы приведено ниже.

![1](https://user-images.githubusercontent.com/91828794/137277527-63461927-5304-4bdd-b823-0ca3720cba66.png)
P.s.: в этой раздаче есть файл на 35 гб. Он как раз будет первым. За ним будут следовать файлы на 34 гб и 33 гб (две другие части этого фильма).

2. Также обнаружилась проблема отображения статуса просмотра для файлов таких торрентов. Программа показывает одинаково заполненную шкалу. Но в разных файлах пользователь может окончить просмотр в разных местах. Хотелось бы объективное отображение статуса по аналогии с торрентами сериалов.

![photo_2021-10-14_10-07-21](https://user-images.githubusercontent.com/91828794/137280543-5de1d518-ad3e-4bfb-b512-c66091b85399.jpg)

**Comment by yumata** [comment]
Короче для .m2ts сделать тайминг для каждого файла свой?)

**Comment by poheto** [comment]
Да вообще, если в раздаче присутствует несколько видеофайлов, отдельный тайминг для каждого самостоятельного файла! 
Но если так нельзя, то хотя бы для файлов vob (dvd с множественными файлами), и m2ts (блюрей с множественными файлами).

**Comment by yumata** [comment]
Добавил отдельные метки для этих файлов.
