### ISSUE TITLE
Добавить возможность убирать рамки и растягивать изображение

### ISSUE THREAD

**Issue by dvt79** [yumata/lampa#54]
Добрый день!

прошу вернуть возможность убирать рамки и растягивать изображение! 

Заранее спасибо!

**Comment by dvt79** [comment]
Я знаю, просьба вернуть, кому не надо включать не будет, либо сделать отдельным виджетом на самсунг если можно, будем Вам очень обязаны!!!



Отправлено из мобильной Почты Mail.ru


вторник, 19 октября 2021 г., 17:26 +1000 от ***@***.***  ***@***.***>:

**Comment by yumata** [comment]
Будет добавлено в следующим обновление.
