### ISSUE TITLE
Просьба пофиксить баг с воспроизведением плеера webOs на самсунг!

### ISSUE THREAD

**Issue by kientyyy** [yumata/lampa#56]
Здравствуйте! 
Не могу запустить плеер webOS на самсунг через Media Station, выбираешь торрент, но плеер не открывается, в чате лампы в телеграме сказали что это Баг. Просьба пофиксит его.
+ 
Добавьте еще парочку плееров с которых можно было бы воспроизводить торренты, потому что у меня на самсунге идет все с фризами, хотя по торрсерву все квадраты прогружены далеко вперёд кэша хватает. 
Прикладываю скрин:
https://sun9-84.userapi.com/impg/VhETNvwQXOh4FxjTR71aHpS5H5AyXMiPOph5lg/lm7yEojcdNQ.jpg?size=573x722&quality=96&sign=474cbb99839a87e4e617825a6d22047d&type=album

С компьютера локально на VLC плеере идёт без фризов, также при той же скорости интернета и веса файла видео, на том же vplay тоже не было фризов. Поэтому думаю дело в плеере.

Заранее благодарен!

**Comment by svkomarov** [comment]
Web OS плеер и не должен запускаться на Samsung. Баг с определением системы в msx. Должен определяться как Samsung и предлагать tizen плеер

**Comment by yumata** [comment]
Думаю что исправлено.
