### ISSUE TITLE
форсированный поиск для torlook

### ISSUE THREAD

**Issue by epexa** [yumata/lampa#64]
данные по сидам и пирам отличаются от актуальных данных
т.е. вот запрос в одно время:
[rutracker](https://rutracker.net/forum/tracker.php?f=1457&nm=Infinity%20War)
[torlook](https://w41.torlook.info/Infinity%20War/size)

результат:
![image](https://user-images.githubusercontent.com/2198826/140046546-fcd5325d-e8a8-4e5d-a3d2-4152ce498613.png)
![image](https://user-images.githubusercontent.com/2198826/140046496-df1769c3-cfc3-4dd5-b47e-5e704798e2ae.png)

предлагаю добавлять параметр forced=1 в запросах к torlook

**Comment by yumata** [comment]
Добавил.
