### ISSUE TITLE
Масштаб изображения На плеере Тайзен

### ISSUE THREAD

**Issue by dvt79** [yumata/lampa#65]
Ддень, прошу добавить возможность убирать рамки и растягивать изображение на плеере тайзен тк на встроенном плеере видео у меня тормозит, на тайзене все летает! На виплее такое было! Заранее спасибо!

**Comment by yumata** [comment]
На тазе нету возможности растягивать, там только два вида масштабирования.

**Comment by dvt79** [comment]
В виплей была такая возможность вроде



Отправлено из мобильной Почты Mail.ru


пятница, 12 ноября 2021 г., 21:09 +1000 от ***@***.***  ***@***.***>:
