### ISSUE TITLE
github pages для раздачи статики

### ISSUE THREAD

**Issue by epexa** [yumata/lampa#69]
чтобы можно было использовать такую ссылку
https://yumata.github.io/lampa-source/dest/online/online.js

пример
https://112q.github.io/1/videocdn.js

**Comment by qarkai** [comment]
https://raw.githubusercontent.com/yumata/lampa-source/main/dest/online/online.js не подойдёт?

**Comment by epexa** [comment]
> https://raw.githubusercontent.com/yumata/lampa-source/main/dest/online/online.js не подойдёт? Или фиксированная версия https://raw.githubusercontent.com/yumata/lampa-source/63fdf23058f1a3cd7cb383722aa5d82cb724e573/plugins/online/online.js

нет, потомучто без github pages оно возвращает как текст, а не как js
![image](https://user-images.githubusercontent.com/2198826/141185492-793338f1-8c89-4cb5-8084-790eaae0166d.png)
![image](https://user-images.githubusercontent.com/2198826/141185427-e1826e40-7fab-4f41-8c43-df447a3b96ae.png)
