### ISSUE TITLE
рассмотреть внешние субтитры opensubtitles

### ISSUE THREAD

**Issue by vip12** [yumata/lampa#70]
Можно рассмотреть вариант прикручивания внешних субтитров [https://opensubtitles.stoplight.io/docs/opensubtitles-api/b3A6Mjg4NDk1NA-search-for-subtitles](url)
есть API и поиск по tmdb_id

**Comment by yumata** [comment]
Все хорошо, но там ограничения на 100 загрузок в день, увы такое нам не подходит.

**Comment by vip12** [comment]
> Все хорошо, но там ограничения на 100 загрузок в день, увы такое нам не подходит.

а если вынести в настройки, кому нужны пусть регаются и вносят свой api key на один аккаунт в теории хватит

**Comment by yumata** [comment]
Хммм, как вариант.

**Comment by yumata** [comment]
Мдя, сложно, при скачке выдает сообщение (You cannot consume this service) я черт знает что оно хочет.
Пока что проблема с сабами это на самсунгах в линейке 2021, может разрабы поправят когда-то.
