### ISSUE TITLE
История просмотров

### ISSUE THREAD

**Issue by kuchag65** [yumata/lampa#71]
Можно ли сделать, чтобы при просмотре контента через online , добавлялось в историю просмотра?

**Comment by SVV198** [comment]
Верните кнопку ввод в приложение то не получается ввести ссылку

**Comment by SVV198** [comment]
На смарт тв самсунг не работают плагины и ссылки тоже не запускаются после последнегр обновления и также пропала кнопка ввода.

**Comment by yumata** [comment]
Добавил в плагин, ждем пока другие обновят.
