### ISSUE TITLE
Не верная вёрстка

### ISSUE THREAD

**Issue by ilya-vdovenko** [yumata/lampa#72]
или какая то особенная на Samsung UE32K5550U (2016 г., К - серия)

сплющены иконки актёров
![актёры](https://user-images.githubusercontent.com/37847271/142036200-b6d225b8-6504-47f8-9ab5-da911446a5a1.png)

клава поплыла
![клава](https://user-images.githubusercontent.com/37847271/142036227-60eef6a5-998c-4761-bde0-7b648d82b434.png)

**Comment by yumata** [comment]
Верстка верная, просто телек старый и не поддерживает фишки html5
