### ISSUE TITLE
Не добавляет в закладки фильмы.

### ISSUE THREAD

**Issue by gorodokdtv** [yumata/lampa#74]
После добавления захожу в закладки нет добавленных фильмов. Вчера установил синхронизацию, добавил токен, думаю что из-за этого проблема. Отключал синхронизацию все нормально работает в закладки добавляет выбранные фильмы.

**Comment by yumata** [comment]
Исправлено, но смотреть одновременно на 2х телевизорах и добавлять в закладки нельзя.
