### ISSUE TITLE
Раздел Новинки

### ISSUE THREAD

**Issue by Report125** [yumata/lampa#75]
Товарищ разработчик
Предлагаю:
1) сделать чтобы в интерфейс настройки, можно было выбрать что после входа в приложения стартовая страница была раздел Новинки ( такого сейчас нет) фильмы и сериалы были собраны все самое новое только вышедшие прошу реально удобно было б с точки пользовательского опыта

**Comment by yumata** [comment]
В themoviedb.org нету новинок, все что есть на главной то и есть в tmdb.
Переключите на источник okko или ivi, там есть новинки и прочие.
