### ISSUE TITLE
BUG: wrong series ordering

### ISSUE THREAD

**Issue by N1ckky** [yumata/lampa#78]
Обнаружил не очень приятную вещь - сортировка серий работает странным образом: 10 серия идёт после первой..
Пример "основание", вышла 10 серия и она в списке стоит после первой. 
![16375201469149066484820179493394](https://user-images.githubusercontent.com/54807747/142774842-6b197735-f77c-4e0e-a484-7719be288551.jpg)

**Comment by yumata** [comment]
Ну тут уже как сортирует торсервер. Правда в таком интерфейсы я мог бы наверно исправить.
