### ISSUE TITLE
Проблема отображения субтитров

### ISSUE THREAD

**Issue by omariok** [yumata/lampa#85]
При просмотре фильмов с торрентов (на Tizen, установлен отдельным виджетом) субтитры странно себя ведут, отображаются только при нажатии кнопок, то есть постоянно приходится нажимать вверх-вниз, если этого не делать, покажет первую ближайшую сказанную фразу и все (*не сразу при нажатии, в нужный момент диалога, допустим нажал кнопку, а речь началась через 15 секунд, из него только первая строчка)

**Comment by yumata** [comment]
Посмотрю что не так.

**Comment by ABCser** [comment]
У меня на Samsung 7 серии, тоже стоит виджет, но субтитры не отображаются вообще. при нажатии на кнопку АБВ в плеере виджета ничего не происходит. Также при выборе аудиодорожки, она не меняется. Речь о просмотре видео с торрента. Про видео онлайн позже отпишусь, не смотрел еще. А так, спасибо большое за виджет и Ваш труд! Когда заработают аудиодорожки и субтитры будет просто идеально!

**Comment by neodimov** [comment]
Привет! У меня в виджете на Samsung все хорошо, но в встроенном плеере нету кнопки включения субтитров. Как их включить?

**Comment by ABCser** [comment]
У меня в стандарнтом плеере появляется иногда кнопка "С", и там можно выбрать субтитры! Но как мне объяснили в чате, субтитры не работают на новых телеках в принципе! На стороне самсунга проблемы. Пока они не пофиксят свой плеер, вроде как не ожидается субтитров!

**Comment by neodimov** [comment]
У меня Samsung 8502 2020 года, и в плеере Tizena субтитры работают, но мне больше нравится встроеный плеер Лампы, а в нем нету кнопки С.

**Comment by OrbitRus** [comment]
Вообще проблема есть с "подложкой"! Она отображения даже когда субтитров нет! Зачем? Не понятно

**Comment by neodimov** [comment]
Подложку можно отключить в настройках Лампы

**Comment by OrbitRus** [comment]
> Подложку можно отключить в настройках Лампы

Я в курсе, раз она у меня была включена! Просто непонятно почему она присутствует, когда нет субтитров

**Comment by neodimov** [comment]
У меня подложка не отображается

**Comment by OrbitRus** [comment]
> У меня подложка не отображается

У меня Самсунг q95t и когда нет субтитров маленькое тёмное окошко внизу постоянно отображается... Пришлось вырубить

**Comment by omariok** [comment]
Если что, выглядит это вот так, чтоб наглядно было понятно что имею ввиду

https://user-images.githubusercontent.com/48212349/145652440-7f1f3864-d3ac-4480-aa61-29da77352906.mp4

**Comment by lbtboy** [comment]
Samsung UE43NU7120RU кнопка "С" присутствует в плеере Tizen и можно выбрать субтитры, но не работает переход от одной серии к другой при просмотре через торрент или онлайн, вылазит ошибка и Lampa намертво виснет. При просмотре через встроенный плеер торрента или онлайн кнопка "С" отсутствует, но плеер работает как надо переход по сериям без зависаний поэтому предпочтение встроенному. Отсюда вопрос как включать на встроенном плеере субтитры?

**Comment by bekarazhan** [comment]
Samsung UE43AU8000UXCE несмотря на выбор субтитр они не отображаются вообще. Наверху люди писали что проблемы на стороне Samsung, действительно ли разработчики Lampa ничего немогут поделать пока те это не исправят? Что тогда остается делать, ждать и надеяться?:) Может стоит написать в тех поддержку самсунг тв) но как им объяснишь это, ведь обычные субтитры у них в своем плеере работают:(

**Comment by yumata** [comment]
> Samsung UE43AU8000UXCE несмотря на выбор субтитр они не отображаются вообще. Наверху люди писали что проблемы на стороне Samsung, действительно ли разработчики Lampa ничего немогут поделать пока те это не исправят? Что тогда остается делать, ждать и надеяться?:) Может стоит написать в тех поддержку самсунг тв) но как им объяснишь это, ведь обычные субтитры у них в своем плеере работают:(

Ждать, на OS версии 2ххх пишут что уже работает, остается ждать когда выкатят обновление для версий 19хх

**Comment by Rakamakafo158** [comment]
Телек UE43AU7100UXCE, субтитров нет нигде. В остальном все отлично, спасибо!
