### ISSUE TITLE
[BUG] Не добавляет в "Мои торренты"

### ISSUE THREAD

**Issue by Roper89** [yumata/lampa#86]
Если из карточки фильма, зайти в "Торренты" и там произвести добавление торрента в "Мои торренты" - он не добавится.

_(более критическая ошибка при добавление торрента в "смотреть позже"  из поискового парсера — #79)_

**Comment by omariok** [comment]
Если правильно понял о чем вы, то "Мои Торренты" предназначены для добавления через торрсерв, чтоб вы могли смотреть свой контент, найденный там, где не ищет встроенный (иностранные ресурсы например)
<img width="668" alt="Снимок экрана 2021-12-05 в 01 33 43" src="https://user-images.githubusercontent.com/48212349/144726575-265c3809-4be8-4373-b05d-b9b830a11387.png">

**Comment by Roper89** [comment]
@omariok попробуйте найти любой торрент в приложение, после на нём зажмите клавишу ОК, для вызова меню действий. Там будет "добавить в мои торренты" вот после этой процедуры, торрент не добавляется не на торсерв, не в раздел закладок, где пункт Торренты.

**Comment by yumata** [comment]
Андроид или телек?

**Comment by Roper89** [comment]
@yumata  Андроид 9

**Comment by yumata** [comment]
Не знаю что за баг, может глюк. У других работает и у меня тоже, все норм.
