### ISSUE TITLE
[BUG] Неверное содержание контента в мультсериалах.

### ISSUE THREAD

**Issue by Roper89** [yumata/lampa#87]
Примеры: 
1) Находим Гайвер (мультсериал 1989г.) постер в карточке мульта отображается верно, запускаем через "Онлайн" и получаем совершенно другой киносериал "Новый агент МакГайвер"
2) Находим в поиске Человек-паук (мультсериал 1994г.) аналогично запускаем и получаем контент других годов не соответствующий постеру и искомой категории. Причём для отображаемого контента есть отдельная карточка.

P.S. при поиске "Покемоны" (мультсериал) в разделе карточки присутствует кнопка "Онлайн", но содержимого в ней нет. Может в таких случаях не отображать данную кнопку?

**Comment by yumata** [comment]
Это не от лампы зависит, а от плагинов, как они находят результаты.
