### ISSUE TITLE
Кнопки влево и вправо на клавиатуре

### ISSUE THREAD

**Issue by ProgressoRU** [yumata/lampa#9]
Предлагаю добавить кнопки влево\вправо на клавиатуре, которые будут передвигать курсор в поле ввода. Будет полезно, если нужно исправить ошибку в ключе апи и для уточнения поискового запроса.

**Comment by yumata** [comment]
Пока не нашел документации как это сделать https://github.com/hodgef/simple-keyboard

**Comment by ProgressoRU** [comment]
Судя по демо с полноразмерной клавиатурой нужно в `layout` добавить `{arrowleft}` и {arrowright} 
https://hodgef.com/simple-keyboard/editor/?d=hodgef/simple-keyboard-npm-demos/tree/full-keyboard

**Comment by yumata** [comment]
Как обычно не чего не работает, у них в гите пишется что эту шляпу самому надо делать(

**Comment by ProgressoRU** [comment]
Я начинал делать, но запнулся. Функционально вроде не очень сложно, проблема в том, что нужно же еще как-то текстовый курсор вывести и тут начинаются проблемы, потому что настоящих инпутов-то нет. И либо делать какой-то велосипед для вывода каретки, либо везде добавлять настоящие инпуты и разбираться с выводом нативных экранных клавиатур на каждой поддерживаемой платформе.

**Comment by yumata** [comment]
Вот и я так подумал, чет сложный велосипед :D
