### ISSUE TITLE
[Request] Микрофризы, плагин онлайн.

### ISSUE THREAD

**Issue by R136a1f22** [yumata/lampa#90]
При воспроизведении «VideoCND» прослеживаются микрофризы.
Хотя с потока «HDREZKA» всё работает плавно но в не лучшем качестве. (720p)
Менял плеер, крутил все доступные настройки, ничего.
Не могли бы вы добавить выбор качества при воспроизведении?

**Comment by Nemiroff** [comment]
Это не поможет, это проблемы VideoCDN
