### ISSUE TITLE
Баг с боковым меню

### ISSUE THREAD

**Issue by rasulich** [yumata/lampa#91]
Навожу на левое боковое меню, когда нажимаю ОК на пульте в нужном месте, нажимается кнопка на самом экране. Т.е. на странице с фильмом крайняя левая кнопка "торренты", при нажатии ок на боковом меню нажимается именно торренты

**Comment by yumata** [comment]
Не чего не понятно, но очень интересно)) Видос бы.

**Comment by rasulich** [comment]
Проблема не актуальна. Где-то через неделю 2 все начало работать нормально :)
Забыл даже, что тут создавал тикет)
