### ISSUE TITLE
Поддержка HLS

### ISSUE THREAD

**Issue by svkomarov** [yumata/lampa#92]
Не хватает mp4 =(
Может есть возможность научить плеер кушать hls?

**Comment by yumata** [comment]
На телевизорах не нужно, там уже есть встроенная поддержка. 
Правда если у вас андроид, может и не работать, но для этого есть внешние плееры.

**Comment by svkomarov** [comment]
Ок, давай базон прикрутим?) писал уже тебе в группе, ты не откликаешься)
Есть уже часть плагина, посмотри, может что-то доработаешь, чтобы работало как надо
