### ISSUE TITLE
Встроенный плеер не работает на Tizen

### ISSUE THREAD

**Issue by DmytroMoroz** [yumata/lampa#94]
При попытке включения фильма онлайн со встроенным плеером выдает ошибку и зависает. Дальше приложение/виджет не работает. После перезагрузки приложение снова работает до входа в плеер.
Телевизор: QE43Q67AAU
Фото ошибок при включении плеера:
![263003892_2117407315064752_2192532575448381691_n](https://user-images.githubusercontent.com/27242400/144672905-20821ddc-38b8-40b0-acea-aeb0f93609e4.jpg)

**Comment by yumata** [comment]
У вас мод, ставьте виджет лампы.
