### ISSUE TITLE
Оценка

### ISSUE THREAD

**Issue by Driuk123** [yumata/lampa#95]
Было бы прикольно, чтобы оценка была на постере,    чтобы не переходить на данный фильм, возможно это воплотить?

**Comment by yumata** [comment]
Вверху показывает сразу оценку и инфу.

**Comment by Driuk123** [comment]
Да показывает, вот только нужно переходить на данный фильм, А я имел ввиду чтобы на всех постерах показывало

**Comment by Darkensand** [comment]
Поддерживаю на постах было бы тоже прикольно
