### ISSUE TITLE
Orsey

### ISSUE THREAD

**Issue by gila357** [yumata/lampa#98]
Здравствуйте, уважаемый разработчик! Телевизор Самсунг с аэромышью или тачпадом (не знаю как правильно называется). В общем указатель есть. В комплекте пульт только такой. Не могу удалить плагины. Долгое нажатие не срабатывает. Огромнейшая просьба как то это исправить.

**Comment by yumata** [comment]
Надо не мышкой нажимать, а клавишей OK долго держать.

**Comment by gila357** [comment]
> Надо не мышкой нажимать, а клавишей OK долго держать.

У меня на пульте нет отдельной кнопки ОК. Она идёт нажатием на тачпаде пульта в середину. Но зажатие не удаляет плагин.

**Comment by yumata** [comment]
Добавил двойной клик.
